export default [
  {
    id: 1,
    name: "Majutused.ee",
    url: "https://majutused.ee",
    image: "https://i.paste.pics/b6739d6ac7d166314517c069a7e0c316.png",
    frontStack: "HTML, CSS, React + JS",
    backStack: "Node.js, connecting to MySQL soon.",
    github: "https://github.com/nuf1k/majutused.ee",
    styles: { locX: 0, locY: 0, transform: "scale(1)" },
  },

  {
    id: 2,
    name: "pumPIM",
    url: "https://pumpim.martencode.ee",
    image: "https://i.paste.pics/2b6f58a1fffcd9d2aa2d7339f1559dfa.png",
    frontStack: "HTML, CSS, Vanilla JS",
    backStack: "Express.js, Node.js, PostgreSQL",
    github: "https://github.com/nuf1k/PUMPIM",
    styles: { locX: 0, locY: 0, transform: "scale(1)" },
  },
  {
    id: 3,
    name: "This portfolio!",
    url: "https://martencode.ee",
    image: "https://i.paste.pics/29ca1954fcff29002820148dec518d08.png",
    frontStack: "HTML, CSS, React + JS",
    backStack: "Runs on Node.js",
    github: "https://github.com/nuf1k/portfolio",
    styles: { locX: 0, locY: 0, transform: "scale(1)" },
  },
  {
    id: 4,
    name: "Majutused.ee",
    url: "https://majutused.ee",
    image: "https://i.paste.pics/95f1eb0db02fddd48b85e3aa835d8da0.png",
    frontStack: "HTML, CSS, React + JS",
    backStack: "Node.js, connecting to MySQL soon.",
    github: "https://github.com/nuf1k/majutused.ee",
    styles: { locX: "center", locY: "center", transform: "scale(1)" },
  },

  {
    id: 5,
    name: "pumPIM",
    url: "https://pumpim.martencode.ee",
    image: "https://i.paste.pics/1b3261d959876ed49050016e7383ce11.png",
    frontStack: "HTML, CSS, Vanilla JS",
    backStack: "Express.js, Node.js, PostgreSQL",
    github: "https://github.com/nuf1k/PUMPIM",
    styles: { locX: 0, locY: 0, transform: "scale(1)" },
  },
  {
    id: 6,
    name: "This portfolio!",
    url: "https://martencode.ee",
    image: "https://i.paste.pics/c111fbd9f4bc8e1125e06aaf134e6328.png",
    frontStack: "HTML, CSS, React + JS",
    backStack: "Runs on Node.js",
    github: "https://github.com/nuf1k/portfolio",
    styles: { locX: 0, locY: 0, transform: "scale(1)" },
  },
];
